### ISSUE TITLE
Finish thermal models

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/ModelingToolkitStandardLibrary.jl#1]

**Comment by ChrisRackauckas** [comment]
Did https://github.com/SciML/ModelingToolkitStandardLibrary.jl/pull/7 solve this @ValentinKaisermayer ?

**Comment by ValentinKaisermayer** [comment]
Depends on what you think "finish" means?
As far as Modelica is concerned the only missing components are controlled sources. Other than that I think it is "finished". 

Unless you also want fluid heat flow as well but that is a whole new issue.

**Comment by ChrisRackauckas** [comment]
I just mean, are all of the blocks there, or a different suggested way to do it? I'll go make docs, and I think what we need for everything is either the block to exist, or some text that explains the "right way" to do it in MTK.

**Comment by ValentinKaisermayer** [comment]
Most of the stuff from [`Thermal.HeatTransfer.Components`](https://doc.modelica.org/Modelica%204.0.0/Resources/helpWSM/Modelica/Modelica.Thermal.HeatTransfer.Components.html) is there. Only the two [controlled sources](https://doc.modelica.org/Modelica%204.0.0/Resources/helpWSM/Modelica/Modelica.Thermal.HeatTransfer.Sources.html) are missing, related to #30. I think it is safe to close.

**Comment by ValentinKaisermayer** [comment]
![plot](https://user-images.githubusercontent.com/50108075/173061172-4c7305f5-1193-4b17-9ca4-8f8dcbc0cae7.png)
