### ISSUE TITLE
Add Mechanical/Translational libraries with both *position* and *velocity* based connectors

### ISSUE THREAD

**Issue by bradcarman** [SciML/ModelingToolkitStandardLibrary.jl#109]
Plan:  

- Put the velocity connector approach under "Mechanical/Translational" and position connector approach under "Mechanical/TranslationalPosition" (or maybe "Mechanical/Positional"). 
- Add documentation to explain the theory and detail the differences.  Will serve as a guide to aid in the decision of which approach to use for one's model.

Both libraries will be as similar as possible, with the only difference being the connector across variable.  Because both libraries will export the same names, mixed use can/should only be done with namespaced use. Mixed use should likely be a rare case.  

A start to the documentation can be found here:  [https://github.com/bradcarman/ModelingToolkitStandardLibrary.jl/blob/main/docs/connections.md](https://github.com/bradcarman/ModelingToolkitStandardLibrary.jl/blob/main/docs/connections.md)

**Comment by ValentinKaisermayer** [comment]
Can you add and demonstrate a component that measures the position for the velocity-based approach?

**Comment by ValentinKaisermayer** [comment]
The rotational library follows the Modelica principles with absolute angle and torque and not the Simscape one with angular velocity and torque. Would you propose to make a separate library too in this case?

**Comment by bradcarman** [comment]
Yes, I'll be explaining the position measurement in my documentation next.  And I'll plan to open a separate PR for the Mechanical/Rotational components.  For now I'll focus on the Translational part to see if everyone agrees with my idea.
