### ISSUE TITLE
ThermalConductor units issue

### ISSUE THREAD

**Issue by kakila** [SciML/ModelingToolkitStandardLibrary.jl#171]
The documentation specifies that G is given in units of Power per Temperature, however this line:
https://github.com/SciML/ModelingToolkitStandardLibrary.jl/blob/f7caceb098cfcc76ef556472fa2f3c6cc924812f/src/Thermal/HeatTransfer/ideal_components.jl#L120

Multiplies G with a factor that is in Power units, giving a result in Power^2 per Temperature.
I guess this line needs to be a division: Q_flow / G; or G needs to be defined differently.

**Comment by kakila** [comment]
Why not define a single device that sets
```
0 ~ C * dT - Q_flow
```
and then make the *Conductor *Resistors just syntax sugar built on top of this element?
This would be less code to maintain

**Comment by ven-k** [comment]
Yes `ConvectiveConductor` equation should be `Q_flow ~ G * dT`. Thanks for catching.
(Issue title needs to be fixed ThermalConductor -> (linked) ConvectiveConductor)


> Why not define a single device that sets

We can define partial blocks and extend them when `systems`, `@parameters`, `@variables` can be reused. As R and G parameters are defined using the given values of R and G, we can't do this.

**Comment by kakila** [comment]
> Yes `ConvectiveConductor` equation should be `Q_flow ~ G * dT`. Thanks for catching. (Issue title needs to be fixed ThermalConductor -> (linked) ConvectiveConductor)
> 
> > Why not define a single device that sets
> 
> We can define partial blocks and extend them when `systems`, `@parameters`, `@variables` can be reused. As R and G parameters are defined using the given values of R and G, we can't do this.

Aren't G and R reciprocals from each other?
