### ISSUE TITLE
Make real docs

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/ModelingToolkitStandardLibrary.jl#8]
This library should probably be done with extensive docstrings and summary pages.

**Comment by AayushSabharwal** [comment]
I'm working on some docstrings in #7. It would probably be useful to have a CI workflow with documenter too

**Comment by ValentinKaisermayer** [comment]
Nice! Apart from the magnetic stuff, which seems to not be setup properly

**Comment by ChrisRackauckas** [comment]
Any follow up can be more specific. Cheers 🎉

**Comment by ChrisRackauckas** [comment]
![plot](https://user-images.githubusercontent.com/1814174/164912906-3e2b294d-2911-4773-82ef-28840b0157db.png)

**Comment by ChrisRackauckas** [comment]
![plot](https://user-images.githubusercontent.com/1814174/164912976-14d3ca38-dd3b-40e5-b19e-8e108df525ff.png)

**Comment by ChrisRackauckas** [comment]
![plot](https://user-images.githubusercontent.com/1814174/164912983-c3f73628-0e19-4e42-b085-4f62ba6f23d1.png)

**Comment by ChrisRackauckas** [comment]
![Screenshot 2022-06-04 085831](https://user-images.githubusercontent.com/1814174/172000112-3579f5cf-c370-48c2-8047-558fbc46aeb6.png)
